# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
