# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dateideas', '0002_ideas_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideas',
            name='author',
        ),
    ]
